from __future__ import annotations

from grave.models.preset import Preset

PRESETS = [
    Preset(
        name="ancient",
        description="GitHub's earliest repos (2008-2010), long since abandoned",
        keywords=[],
        created_range="2008-01-01..2010-12-31",
        stars_range=">=1",
        pushed="<2014-01-01",
        category="archaeology",
        sort="stars",
    ),
    Preset(
        name="forgotten",
        description="Old repos with few stars, untouched for a decade",
        keywords=[],
        created_range="2008-01-01..2015-12-31",
        stars_range="0..5",
        pushed="<2016-01-01",
        category="archaeology",
        sort="updated",
    ),
    Preset(
        name="graveyard",
        description="Projects their owners formally archived",
        keywords=[],
        created_range="2008-01-01..2020-12-31",
        pushed="<2020-01-01",
        archived=True,
        category="archaeology",
        sort="stars",
    ),
    Preset(
        name="one-commit",
        description="Repos with minimal activity, frozen in time",
        keywords=[],
        created_range="2008-01-01..2015-12-31",
        stars_range="0..3",
        pushed="<2016-01-01",
        category="archaeology",
        sort="updated",
    ),
    Preset(
        name="abandoned-10y",
        description="Repos untouched for 10+ years",
        keywords=[],
        created_range="2008-01-01..2016-12-31",
        pushed="<2016-01-01",
        category="archaeology",
        sort="stars",
    ),
    Preset(
        name="dotfiles-ancient",
        description="The earliest dotfiles and system configs",
        keywords=["dotfiles", "vimrc", "bashrc", "zshrc"],
        created_range="2008-01-01..2012-12-31",
        pushed="<2015-01-01",
        category="archaeology",
        sort="stars",
    ),
    Preset(
        name="tiny-gems",
        description="Starred repos under 10 KB: whole ideas that fit on one screen",
        keywords=[],
        created_range="2008-01-01..2015-12-31",
        stars_range=">=50",
        pushed="<2017-01-01",
        size="<10",
        category="archaeology",
        sort="stars",
    ),
]
