from __future__ import annotations

from grave.models.preset import Preset

PRESETS = [
    Preset(
        name="digital-utopia",
        description="Digital democracy and virtual world experiments",
        keywords=["democracy", "society", "virtual world", "utopia", "collective"],
        created_range="2008-01-01..2015-12-31",
        pushed="<2018-01-01",
        category="culture",
        sort="stars",
    ),
    Preset(
        name="cyber-relics",
        description="Early internet culture and cyberspace projects",
        keywords=["cyberspace", "information superhighway", "bulletin board"],
        created_range="2008-01-01..2012-12-31",
        pushed="<2015-01-01",
        match="name,description",
        category="culture",
        sort="stars",
    ),
    Preset(
        name="irc-era",
        description="IRC bots, clients, and scripts",
        keywords=["irc", "irc bot", "irc client", "eggdrop"],
        created_range="2008-01-01..2015-12-31",
        pushed="<2018-01-01",
        match="name,description",
        category="culture",
        sort="stars",
    ),
    Preset(
        name="myspace-era",
        description="Social network widgets and MySpace-era tools",
        keywords=["myspace", "widget", "social network", "friendster"],
        created_range="2008-01-01..2012-12-31",
        pushed="<2015-01-01",
        match="name,description",
        category="culture",
        sort="stars",
    ),
    Preset(
        name="sourceforge-refugees",
        description="Projects migrated from SourceForge",
        keywords=["sourceforge", "migrated", "cvs2git", "svn2git"],
        created_range="2008-01-01..2015-12-31",
        pushed="<2018-01-01",
        category="culture",
        sort="stars",
    ),
    Preset(
        name="google-code-refugees",
        description="Projects exiled by the Google Code shutdown",
        keywords=["googlecode", "exported from code.google.com"],
        created_range="2008-01-01..2016-12-31",
        pushed="<2019-01-01",
        category="culture",
        sort="stars",
    ),
    Preset(
        name="dead-social",
        description="Clients and bots for social networks that no longer exist",
        keywords=["vine api", "google plus api", "friendfeed", "orkut"],
        created_range="2008-01-01..2016-12-31",
        pushed="<2020-01-01",
        category="culture",
        sort="stars",
    ),
    Preset(
        name="bbs-era",
        description="Bulletin board systems and BBS door games",
        keywords=["bbs", "bulletin board", "door game", "fidonet", "telnet"],
        created_range="2008-01-01..2015-12-31",
        pushed="<2016-01-01",
        match="name,description",
        category="culture",
        sort="stars",
    ),
    Preset(
        name="crypto-og",
        description="Early blockchain and cryptocurrency (2009-2013)",
        keywords=["bitcoin", "blockchain", "cryptocurrency", "mining", "satoshi"],
        created_range="2009-01-01..2013-12-31",
        pushed="<2016-01-01",
        category="culture",
        sort="stars",
    ),
    Preset(
        name="esolangs",
        description="Esoteric languages: Brainfuck, Befunge, Malbolge and stranger",
        keywords=["esolang", "brainfuck", "befunge", "malbolge"],
        created_range="2008-01-01..2015-12-31",
        pushed="<2018-01-01",
        category="culture",
        sort="stars",
    ),
    Preset(
        name="demoscene",
        description="Size-coded intros and tracker players from the demoscene",
        keywords=["demoscene", "4k intro", "64k intro", "tracker"],
        created_range="2008-01-01..2015-12-31",
        pushed="<2018-01-01",
        match="name,description",
        category="culture",
        sort="stars",
    ),
]
