"""The stories behind the repos: first commits, resolutions, hackathons, pitches."""

from __future__ import annotations

from grave.models.preset import Preset

PRESETS = [
    Preset(
        name="hello-world-graveyard",
        description="Zero-star hello-worlds from 2008-2010 whose authors never came back",
        keywords=["hello-world", "helloworld"],
        created_range="2008-01-01..2010-12-31",
        stars_range="0..0",
        pushed="<2012-01-01",
        match="name",
        category="human",
        sort="updated",
    ),
    Preset(
        name="my-first-repo",
        description="Someone's very first repository, abandoned after the first push",
        keywords=["my first", "first repo", "test repo"],
        created_range="2008-01-01..2012-12-31",
        stars_range="0..1",
        pushed="<2014-01-01",
        match="name,description",
        category="human",
        sort="updated",
    ),
    Preset(
        name="learning-x",
        description="'Learning Rust/Haskell/Clojure/Go' repos that stopped after a month",
        keywords=["learning rust", "learning haskell", "learning clojure", "learning go"],
        created_range="2010-01-01..2016-12-31",
        stars_range="0..3",
        pushed="<2017-01-01",
        match="name,description",
        category="human",
        sort="updated",
    ),
    Preset(
        name="resolution-2013",
        description="Started in the first week of 2013, dead by spring",
        keywords=[],
        created_range="2013-01-01..2013-01-07",
        stars_range=">=3",
        pushed="<2013-04-01",
        category="human",
        sort="stars",
    ),
    Preset(
        name="hackathon-corpses",
        description="Built in a weekend, never touched again",
        keywords=["hackathon", "hack day", "48 hours"],
        created_range="2010-01-01..2016-12-31",
        pushed="<2018-01-01",
        category="human",
        sort="stars",
    ),
    Preset(
        name="bootcamp-projects",
        description="Coding bootcamp final projects and capstones",
        keywords=["bootcamp", "final project", "capstone"],
        created_range="2012-01-01..2016-12-31",
        pushed="<2018-01-01",
        category="human",
        sort="stars",
    ),
    Preset(
        name="uber-for-x",
        description="'The Uber for X' startup pitches, frozen mid-pivot",
        keywords=['"uber for"', '"airbnb for"', '"tinder for"', '"netflix of"'],
        created_range="2011-01-01..2016-12-31",
        pushed="<2018-01-01",
        match="description",
        category="human",
        sort="stars",
    ),
    Preset(
        name="todo-app-graveyard",
        description="The universal starter project, ten thousand times over",
        keywords=["todo app", "todo list", "todomvc"],
        created_range="2010-01-01..2015-12-31",
        pushed="<2017-01-01",
        category="human",
        sort="stars",
    ),
    Preset(
        name="rewrite-stalled",
        description="Rewrites in Rust or Go that stalled partway",
        keywords=['"rewrite in rust"', '"rewrite in go"', '"rewritten in"'],
        created_range="2014-01-01..2019-12-31",
        pushed="<2021-01-01",
        category="human",
        sort="stars",
    ),
]
