"""Completion scripts are generated from the live argparse tree, so they never drift."""

from __future__ import annotations

import argparse

_BASH_TEMPLATE = """\
# grave shell completion — generated by 'grave completion'
_grave() {
    local cur prev
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    if [[ "$prev" == "--preset" ]]; then
        COMPREPLY=( $(compgen -W "__PRESETS__" -- "$cur") )
        return
    fi
    if (( COMP_CWORD == 1 )); then
        COMPREPLY=( $(compgen -W "__COMMANDS__" -- "$cur") )
        return
    fi
    case "${COMP_WORDS[1]}" in
__CASES__
        *) COMPREPLY=() ;;
    esac
}
complete -F _grave grave
"""

_ZSH_PREAMBLE = """\
# grave shell completion (zsh via bashcompinit) — generated by 'grave completion'
autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit
"""


def _subcommand_words(root: argparse.ArgumentParser) -> dict[str, list[str]]:
    """Map each subcommand to its completable words (flags + positional choices)."""
    result: dict[str, list[str]] = {}
    for action in root._actions:
        choices = getattr(action, "choices", None)
        if not isinstance(choices, dict):
            continue
        for name, sub in choices.items():
            if not isinstance(sub, argparse.ArgumentParser):
                continue
            words: list[str] = []
            for sub_action in sub._actions:
                if sub_action.option_strings:
                    words.extend(sub_action.option_strings)
                elif sub_action.choices is not None:
                    words.extend(str(c) for c in sub_action.choices)
            result[str(name)] = words
    return result


def render_completion_script(root: argparse.ArgumentParser, shell: str) -> str:
    """Render the completion script for the given shell ('bash' or 'zsh')."""
    from grave.config.presets import PRESETS

    subcommands = _subcommand_words(root)
    cases = "\n".join(
        f'        {name}) COMPREPLY=( $(compgen -W "{" ".join(words)}" -- "$cur") ) ;;'
        for name, words in subcommands.items()
    )
    script = (
        _BASH_TEMPLATE.replace("__PRESETS__", " ".join(p.name for p in PRESETS))
        .replace("__COMMANDS__", " ".join(subcommands))
        .replace("__CASES__", cases)
    )
    if shell == "zsh":
        return _ZSH_PREAMBLE + script
    return script


def cmd_completion(args: argparse.Namespace) -> None:
    """Print a completion script for the requested shell."""
    print(render_completion_script(args.root_parser, args.shell), end="")
